export const FOOD_DESCRIPTION_TEMPLATES = [
  // Classic & Elegant
  "Indulge in our mouth-watering [Name], crafted with the freshest ingredients and a touch of our signature [Flavor] sauce. It's an absolute must-try with a [Spice] kick!",
  "A classic favorite! Our [Name] is slow-cooked to perfection, offering a rich and hearty experience that will leave you craving more.",
  "Treat yourself to the exquisite taste of our [Name]. Perfectly balanced flavors make this a delightful choice for any time of the day.",
  "Our [Name] is a culinary masterpiece, featuring a crispy exterior and a tender, flavorful inside. Served fresh and hot!",
  "Experience a burst of flavors with every bite of our [Name]. It features a [Spice] profile that perfectly complements its [Flavor] notes.",
  "Light, refreshing, and incredibly tasty. Our [Name] is prepared daily using locally sourced ingredients for maximum freshness.",
  "Satisfy your hunger with our generous portion of [Name]. It’s a wholesome dish that packs a serious punch of flavor.",
  "Dive into the rich and creamy goodness of our [Name]. This dish is a comfort food classic, elevated with our chef's special seasoning.",
  "Our [Name] offers a delightful crunch followed by a tender, melt-in-your-mouth experience. Perfect as a quick bite or a full meal.",
  "A beautiful harmony of savory and sweet! The [Name] is an iconic dish on our menu, finished with a delightful [Flavor] glaze.",
  "Spicy, tangy, and utterly delicious. The [Name] brings the heat with a [Spice] finish that spice lovers will absolutely adore.",
  "Enjoy the rustic charm of our [Name], made using traditional recipes passed down through generations. A true taste of home.",
  "Our [Name] is a vibrant and colorful dish, packed with essential nutrients and bursting with zesty flavors.",
  "Gourmet dining meets street food soul in our [Name]. It's a quick, delicious, and incredibly satisfying option for foodies.",
  "The [Name] is a fan favorite for a reason! It’s juicy, flavorful, and cooked to order just the way you like it.",
  "Elevate your dining experience with our [Name]. A sophisticated blend of [Flavor] aromatics and a bold [Spice] undertone.",
  "Crispy on the outside, soft and fluffy on the inside. Our [Name] is the ultimate comfort food for any occasion.",
  "Take a flavorful journey with our [Name]. This dish features exotic spices and a rich, robust aroma that captivates the senses.",
  "Our [Name] is grilled to perfection, locking in all the natural juices and smoky flavors you love.",
  "A refreshing and zesty delight! The [Name] is the perfect choice for a light yet incredibly fulfilling meal.",
  "Bold, savory, and undeniably satisfying. Our [Name] is served piping hot with a side of our house-made [Flavor] dip.",
  "The [Name] is a true crowd-pleaser, featuring a delightful mix of textures and a deeply savory profile.",
  "Savor the rich, deep flavors of our [Name]. Every bite is a testament to our chef’s dedication to quality and taste.",
  "Our [Name] is a delightful fusion of classic cooking techniques and modern, bold [Flavor] accents.",
  "Treat your tastebuds to the sweet and savory magic of our [Name]. It's a wonderfully balanced dish that hits all the right notes.",
  "The [Name] is famously tender and packed with a [Spice] punch that lingers beautifully on the palate.",
  "Warm up with a comforting bowl of our [Name]. It’s rich, aromatic, and deeply satisfying down to the last drop.",
  "Our [Name] is an irresistible treat, featuring a golden, flaky crust and a deliciously savory filling.",
  "A fresh take on a beloved classic. The [Name] combines timeless flavors with a surprisingly delightful [Flavor] twist.",
  "Get ready for a flavor explosion! Our [Name] is heavily seasoned and cooked to crispy perfection.",
  "The [Name] is a wholesome, hearty dish that’s perfect for sharing with friends and family around the table.",
  "Our [Name] is delicately seasoned to highlight its natural flavors, resulting in a clean, elegant, and delicious dish.",
  "Feast on the bold, fiery flavors of our [Name]. It boasts a [Spice] level that will surely satisfy your cravings for heat.",
  "The [Name] is a luscious, creamy delight that serves as the ultimate indulgence for any food lover.",
  "Enjoy the smoky, charred goodness of our [Name]. It’s barbecue perfection, served fresh off the grill.",
  "Our [Name] is a beautifully balanced dish, offering a light crunch and a refreshing, tangy [Flavor] aftertaste.",
  "A symphony of flavors in every bite. The [Name] is meticulously crafted to ensure a perfect eating experience.",
  "Our [Name] is an incredibly satisfying dish, featuring a rich, robust sauce and a tender, mouth-watering core.",
  "The [Name] is a vibrant mix of fresh ingredients, tossed in a zesty [Flavor] dressing for a lively flavor profile.",
  "Indulge in the ultimate comfort of our [Name]. It’s hearty, warm, and guaranteed to make your day better.",
  "Our [Name] is a sweet and savory masterpiece, offering a complex flavor profile that is truly unforgettable.",
  "The [Name] is packed with a serious [Spice] kick, balanced perfectly by a cooling, savory undertone.",
  "A classic dish done right. Our [Name] is simple, elegant, and relies on the highest quality ingredients for its amazing taste.",
  "Our [Name] is an absolute flavor bomb! It’s juicy, tender, and coated in our signature house [Flavor] rub.",
  "The [Name] is a deeply aromatic dish, slow-cooked for hours to ensure every bite is packed with maximum flavor.",
  "A delightful crunch gives way to a soft, savory center in our [Name]. It’s an incredibly addictive snack or appetizer.",
  "Our [Name] is a refreshing, cool, and crisp dish that serves as the perfect palate cleanser or light meal.",
  "The [Name] is a rich and decadent option, featuring layers of incredible flavor and a beautiful presentation.",
  "Enjoy the hearty, fulfilling goodness of our [Name]. It’s a classic staple that never goes out of style.",
  "Our [Name] is a fiery, bold dish that takes no prisoners! The [Spice] heat level is perfect for the adventurous eater.",
  "The [Name] is a delightful mix of savory and sweet, creating a unique flavor profile that you won’t find anywhere else.",
  "Our [Name] is cooked to absolute perfection, offering a tender bite and a deeply satisfying, savory finish.",
  "The [Name] is a vibrant, energetic dish that pairs perfectly with a cold beverage and good company.",
  "Indulge in the creamy, dreamy goodness of our [Name]. It’s an incredibly comforting dish that hits the spot every time.",
  "Our [Name] is an expertly crafted dish, balancing a bold [Flavor] sauce with a subtle, underlying [Spice] kick.",
  "The [Name] is a light, airy, and incredibly flavorful choice for those looking for something beautifully simple.",
  "Our [Name] is a massive, hearty feast that is guaranteed to conquer even the biggest of appetites.",
  "The [Name] is a delicate, refined dish that highlights the pure, unadulterated flavors of its premium ingredients.",
  "Our [Name] is a wonderfully messy, incredibly delicious dish that requires you to roll up your sleeves and dig in!",
  "The [Name] is a timeless classic, offering a warm, familiar taste that feels just like a comforting hug.",

  // Witty, Hungry, Craving Style
  "Drooling yet? Our [Name] is literally what dreams are made of. Dangerously addictive and [Spice] to perfection.",
  "Late night cravings? Mid-day slump? This [Name] is the ultimate cure. One bite and you'll be hooked on that [Flavor] goodness.",
  "Cancel your plans, because you’re staying in with our [Name]. It’s a cozy, messy, and ridiculously tasty affair.",
  "Look at it. Just look at it. Our [Name] doesn't just taste amazing, it’s a [Spice] work of art that demands to be devoured.",
  "We don’t want to be dramatic, but our [Name] might just change your life. Yeah, that [Flavor] kick is exactly what you need right now.",
  "Hungry? Like, 'could eat a horse' hungry? Skip the horse and tackle our massive [Name] instead. You can thank us later.",
  "Warning: Our [Name] is highly addictive. The [Flavor] magic inside will have you ordering a second round before you finish the first.",
  "Craving something that hits the spot? This [Name] is like a warm hug for your stomach, but with a surprisingly [Spice] attitude.",
  "Say goodbye to boring food. The [Name] is here to rescue your tastebuds with an absolute explosion of [Flavor].",
  "Don't fight the urge. You know you want the [Name]. It’s rich, it’s decadent, and it’s staring right at you.",
  "Get ready to unbutton your pants. Our [Name] is a gloriously heavy, ridiculously good indulgence.",
  "Stressed, blessed, and [Name]-obsessed. Seriously, this [Spice] masterpiece is the therapy you deserve today.",
  "Imagine the best thing you’ve ever eaten. Now multiply it by ten. That’s our [Name], drenched in pure [Flavor] perfection.",
  "Caution: Consuming our [Name] may cause spontaneous happy dances and an overwhelming sense of culinary bliss.",
  "Craving a little heat? The [Name] is unapologetically [Spice] and absolutely not messing around.",
  "We could describe the [Name] in detail, but honestly, you just need to put it in your mouth. You won't regret it.",
  "The [Name] is the bad boy of our menu. It’s messy, bold, and brings a [Spice] attitude you can't resist.",
  "You deserve a treat, and our [Name] is exactly it. It’s basically self-care on a plate.",
  "Stop scrolling and start eating. The [Name] is the [Flavor] packed answer to whatever question your stomach is asking.",
  "If the [Name] was a person, it would be the life of the party. Bold, incredibly [Spice], and leaves you wanting more.",
  "Let’s be real, you’re only here for the [Name]. And we don't blame you, that [Flavor] goodness is undefeated.",
  "Your diet starts tomorrow. Today is reserved exclusively for devouring our glorious [Name].",
  "We won't judge if you don't want to share the [Name]. Frankly, with this [Spice] profile, we wouldn't either.",
  "There’s hungry, and then there’s '[Name]' hungry. Satisfy the beast with our most crave-worthy dish.",
  "Prepare for a flavor riot. The [Name] pulls no punches, delivering a [Flavor] knockout in every single bite.",
  "Feeling adventurous? The [Name] is a wildcard of [Flavor] and a [Spice] finish that will keep you guessing.",
  "This isn't just a meal. The [Name] is an entire mood. Come get your fix.",
  "Our [Name] is the ultimate flex. Show your stomach who's boss with this [Spice], savory legend.",
  "You think you know good food? The [Name] is about to redefine everything you thought you knew about [Flavor].",
  "It’s cheesy, it’s saucy, it’s everything you’ve been dreaming about. The [Name] is calling your name.",
  "Don't let the [Name] intimidate you. Yes, it’s [Spice], but you're tough enough to handle it... right?",
  "We packed so much [Flavor] into the [Name], we almost broke the laws of physics. Enjoy the delicious consequences.",
  "The [Name]: because sometimes you just need to eat your feelings, and they taste absolutely amazing.",
  "A little bit of sweet, a whole lot of [Flavor], and a dangerous amount of 'I can't stop eating this'. Meet the [Name].",
  "You know that feeling when the food is so good you have to close your eyes? Yeah, the [Name] does that.",
  "The [Name] is practically begging to be eaten. Don't be rude, answer the call and enjoy the [Spice] ride.",
  "Good vibes and even better food. The [Name] is an instant mood booster powered by serious [Flavor].",
  "Life is short. Eat the [Name]. Seriously, why are you still reading this when you could be eating?",
  "We took all the best things in the world and put them into the [Name]. It’s a [Spice] miracle, honestly.",
  "The [Name] is our love letter to everyone who takes their cravings seriously. Prepare to be swept off your feet."
];
