export interface MenuAddOn {
  id: number;
  name: string;
  price: number;
}

export interface MenuItem {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
  rating: number;
  time: string;
  sizes?: { label: string; grams: string; priceAdd: number }[];
  addOns: MenuAddOn[];
  category: string;
  tags: string[];
  badge?: "Most Liked" | "Bestseller" | "New";
  isVeg: boolean;
  hasEgg: boolean;
  hasOnionGarlic: boolean;
}

export interface Pairing {
  id: number;
  name: string;
  price: number;
  image: string;
}

export const menuCategories = [
  "Main Dishes",
  "Vegan",
  "Street Food",
  "Desserts",
  "Drinks",
  "Alcohol",
] as const;

export type MenuCategory = (typeof menuCategories)[number];

export const menuItems: MenuItem[] = [
  {
    id: 1001,
    name: "Rotini Delight",
    description: "Hand-rolled rotini pasta tossed in a creamy sun-dried tomato pesto with roasted pine nuts and fresh basil.",
    price: 580,
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?q=80&w=800&auto=format&fit=crop",
    rating: 4.9,
    time: "25 mins",
    sizes: [
      { label: "Regular", grams: "380g", priceAdd: 0 },
      { label: "Medium", grams: "480g", priceAdd: 80 },
      { label: "Large", grams: "560g", priceAdd: 150 },
    ],
    addOns: [
      { id: 2001, name: "Extra Cheese", price: 80 },
      { id: 2002, name: "Grilled Chicken", price: 120 },
      { id: 2003, name: "Truffle Oil", price: 100 },
      { id: 2004, name: "Garlic Bread", price: 60 },
    ],
    category: "Main Dishes",
    tags: ["pasta", "italian"],
    badge: "Bestseller",
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1002,
    name: "Spicy Chicken Tikka Bowl",
    description: "Tandoori-charred chicken tikka over fragrant basmati rice with mint chutney, pickled onions, and raita.",
    price: 520,
    image: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?q=80&w=800&auto=format&fit=crop",
    rating: 4.7,
    time: "30 mins",
    sizes: [
      { label: "Regular", grams: "380g", priceAdd: 0 },
      { label: "Medium", grams: "480g", priceAdd: 70 },
      { label: "Large", grams: "560g", priceAdd: 130 },
    ],
    addOns: [
      { id: 2005, name: "Extra Tikka", price: 100 },
      { id: 2006, name: "Naan Bread", price: 60 },
      { id: 2007, name: "Spicy Sauce", price: 30 },
    ],
    category: "Main Dishes",
    tags: ["indian", "bowl"],
    badge: "Most Liked",
    isVeg: false,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1003,
    name: "Nepali Thali Set",
    description: "A complete Nepali feast: steamed rice, dal, seasonal tarkari, achar, spinach, papad, and a side of gundruk soup.",
    price: 380,
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=800&auto=format&fit=crop",
    rating: 4.6,
    time: "35 mins",
    addOns: [
      { id: 2008, name: "Chicken Curry", price: 100 },
      { id: 2009, name: "Mutton Curry", price: 150 },
      { id: 2010, name: "Extra Rice", price: 30 },
      { id: 2011, name: "Ghee", price: 20 },
    ],
    category: "Main Dishes",
    tags: ["nepali", "thali"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1004,
    name: "Grilled Salmon Teriyaki",
    description: "Wild-caught salmon fillet glazed with homemade teriyaki, served with steamed jasmine rice and edamame.",
    price: 890,
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=800&auto=format&fit=crop",
    rating: 4.8,
    time: "28 mins",
    addOns: [
      { id: 2012, name: "Miso Soup", price: 70 },
      { id: 2013, name: "Extra Rice", price: 40 },
      { id: 2014, name: "Wasabi", price: 20 },
    ],
    category: "Main Dishes",
    tags: ["japanese", "seafood"],
    badge: "New",
    isVeg: false,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1005,
    name: "Buddha Bowl",
    description: "Quinoa, roasted sweet potato, chickpeas, avocado, kale, beetroot hummus, and tahini lemon dressing.",
    price: 450,
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop",
    rating: 4.5,
    time: "20 mins",
    addOns: [
      { id: 2015, name: "Extra Avocado", price: 80 },
      { id: 2016, name: "Tofu", price: 60 },
      { id: 2017, name: "Feta Cheese", price: 60 },
    ],
    category: "Vegan",
    tags: ["healthy", "bowl"],
    badge: "Most Liked",
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
  {
    id: 1006,
    name: "Vegan Pad Thai",
    description: "Rice noodles wok-tossed with tofu, crushed peanuts, bean sprouts, lime, and sweet tamarind sauce.",
    price: 390,
    image: "https://images.unsplash.com/photo-1559314809-0d155014e29e?q=80&w=800&auto=format&fit=crop",
    rating: 4.4,
    time: "22 mins",
    addOns: [
      { id: 2018, name: "Extra Tofu", price: 50 },
      { id: 2019, name: "Peanut Crumble", price: 30 },
      { id: 2020, name: "Chili Flakes", price: 10 },
    ],
    category: "Vegan",
    tags: ["thai", "noodles"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1007,
    name: "Mushroom Risotto",
    description: "Creamy arborio rice cooked with wild porcini mushrooms, white wine, parmesan, and fresh thyme.",
    price: 550,
    image: "https://images.unsplash.com/photo-1476124369491-e7addf5db371?q=80&w=800&auto=format&fit=crop",
    rating: 4.7,
    time: "30 mins",
    addOns: [
      { id: 2021, name: "Truffle Shavings", price: 150 },
      { id: 2022, name: "Extra Parmesan", price: 60 },
    ],
    category: "Vegan",
    tags: ["italian", "risotto"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1008,
    name: "Chicken Momo (Steam)",
    description: "8 pieces of handcrafted steamed dumplings with juicy chicken filling and fiery tomato achar.",
    price: 250,
    image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?q=80&w=800&auto=format&fit=crop",
    rating: 4.8,
    time: "20 mins",
    addOns: [
      { id: 2023, name: "Extra Momo (4 pcs)", price: 80 },
      { id: 2024, name: "Jhol Achar", price: 40 },
      { id: 2025, name: "Spicy Sauce", price: 30 },
    ],
    category: "Street Food",
    tags: ["nepali", "dumpling"],
    badge: "Bestseller",
    isVeg: false,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1009,
    name: "Chatpate",
    description: "Crispy puffed rice with chopped onions, tomatoes, cilantro, lemon juice, and a medley of Nepali spices.",
    price: 120,
    image: "https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7?q=80&w=800&auto=format&fit=crop",
    rating: 4.3,
    time: "10 mins",
    addOns: [
      { id: 2026, name: "Extra Spicy", price: 10 },
      { id: 2027, name: "Peanuts", price: 20 },
    ],
    category: "Street Food",
    tags: ["nepali", "snack"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1010,
    name: "Pani Puri",
    description: "Crispy hollow puris filled with spicy potato mixture and tangy mint water. A burst of flavors in every bite.",
    price: 150,
    image: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?q=80&w=800&auto=format&fit=crop",
    rating: 4.5,
    time: "12 mins",
    addOns: [
      { id: 2028, name: "Sweet Water", price: 20 },
      { id: 2029, name: "Extra Puris", price: 40 },
    ],
    category: "Street Food",
    tags: ["indian", "snack"],
    badge: "Most Liked",
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: true,
  },
  {
    id: 1011,
    name: "Chocolate Lava Cake",
    description: "Warm chocolate fondant with a molten center, dusted with cocoa and served with vanilla bean ice cream.",
    price: 320,
    image: "https://images.unsplash.com/photo-1551024601-bec78aea704b?q=80&w=800&auto=format&fit=crop",
    rating: 4.9,
    time: "25 mins",
    addOns: [
      { id: 2030, name: "Extra Ice Cream", price: 60 },
      { id: 2031, name: "Whipped Cream", price: 30 },
      { id: 2032, name: "Berry Compote", price: 50 },
    ],
    category: "Desserts",
    tags: ["chocolate", "cake"],
    badge: "Bestseller",
    isVeg: true,
    hasEgg: true,
    hasOnionGarlic: false,
  },
  {
    id: 1012,
    name: "Mango Panna Cotta",
    description: "Silky Italian custard infused with Alphonso mango purée, topped with passion fruit coulis.",
    price: 280,
    image: "https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=800&auto=format&fit=crop",
    rating: 4.6,
    time: "15 mins",
    addOns: [
      { id: 2033, name: "Fresh Berries", price: 50 },
      { id: 2034, name: "Mint Garnish", price: 10 },
    ],
    category: "Desserts",
    tags: ["italian", "mango"],
    isVeg: true,
    hasEgg: true,
    hasOnionGarlic: false,
  },
  {
    id: 1013,
    name: "Gulab Jamun",
    description: "Soft, spongy milk-solid dumplings soaked in rose-cardamom sugar syrup. Served warm.",
    price: 180,
    image: "https://images.unsplash.com/photo-1666190059789-beb2f08a8d9f?q=80&w=800&auto=format&fit=crop",
    rating: 4.4,
    time: "15 mins",
    addOns: [
      { id: 2035, name: "Ice Cream Side", price: 50 },
      { id: 2036, name: "Rabri", price: 40 },
    ],
    category: "Desserts",
    tags: ["indian", "sweet"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
  {
    id: 1014,
    name: "Masala Chai",
    description: "Strong Nepali black tea brewed with ginger, cardamom, cinnamon, and whole milk. Sweetened to taste.",
    price: 80,
    image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?q=80&w=800&auto=format&fit=crop",
    rating: 4.7,
    time: "8 mins",
    addOns: [
      { id: 2037, name: "Extra Strong", price: 10 },
      { id: 2038, name: "Oat Milk", price: 30 },
    ],
    category: "Drinks",
    tags: ["tea", "nepali"],
    badge: "Most Liked",
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
  {
    id: 1015,
    name: "Iced Matcha Latte",
    description: "Ceremonial-grade matcha whisked with oat milk, poured over ice. Subtly sweet and earthy.",
    price: 350,
    image: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a?q=80&w=800&auto=format&fit=crop",
    rating: 4.5,
    time: "10 mins",
    addOns: [
      { id: 2039, name: "Extra Shot", price: 50 },
      { id: 2040, name: "Vanilla Syrup", price: 30 },
    ],
    category: "Drinks",
    tags: ["matcha", "cold"],
    badge: "New",
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
  {
    id: 1016,
    name: "Fresh Lime Soda",
    description: "Freshly squeezed lime juice with sparkling soda, a pinch of black salt, and mint leaves.",
    price: 120,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed514?q=80&w=800&auto=format&fit=crop",
    rating: 4.3,
    time: "5 mins",
    addOns: [
      { id: 2041, name: "Ginger", price: 10 },
      { id: 2042, name: "Honey", price: 20 },
    ],
    category: "Drinks",
    tags: ["cold", "refreshing"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
  {
    id: 1017,
    name: "Craft Wheat Beer",
    description: "Locally brewed unfiltered wheat beer with hints of citrus, coriander, and a smooth golden finish.",
    price: 450,
    image: "https://images.unsplash.com/photo-1535958636474-b021ee887b13?q=80&w=800&auto=format&fit=crop",
    rating: 4.4,
    time: "5 mins",
    addOns: [
      { id: 2043, name: "Beer Nuts", price: 80 },
      { id: 2044, name: "Lime Wedge", price: 10 },
    ],
    category: "Alcohol",
    tags: ["beer", "craft"],
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
  {
    id: 1018,
    name: "Himalayan Mule",
    description: "Local vodka, fresh ginger beer, lime juice, and Timur pepper — a Nepali twist on the Moscow Mule.",
    price: 550,
    image: "https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?q=80&w=800&auto=format&fit=crop",
    rating: 4.6,
    time: "8 mins",
    addOns: [
      { id: 2045, name: "Double Shot", price: 200 },
      { id: 2046, name: "Extra Ginger Beer", price: 60 },
    ],
    category: "Alcohol",
    tags: ["cocktail", "nepali"],
    badge: "New",
    isVeg: true,
    hasEgg: false,
    hasOnionGarlic: false,
  },
];

export const pairings: Pairing[] = [
  { id: 3001, name: "Garlic Bread", price: 120, image: "https://images.unsplash.com/photo-1619535860434-ba1d8fa12536?q=80&w=400&auto=format&fit=crop" },
  { id: 3002, name: "Caesar Salad", price: 220, image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?q=80&w=400&auto=format&fit=crop" },
  { id: 3003, name: "Tomato Soup", price: 180, image: "https://images.unsplash.com/photo-1547592166-23ac45744acd?q=80&w=400&auto=format&fit=crop" },
  { id: 3004, name: "Iced Tea", price: 140, image: "https://images.unsplash.com/photo-1556679343-c7306c1976bc?q=80&w=400&auto=format&fit=crop" },
];
