// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// `import "dotenv/config"` loads ONLY `.env`. Next.js loads `.env.local` first
// and `.env` second, so with a `.env.local`-only setup (what `vercel env pull`
// produces) every Prisma CLI command failed with P4003 "No URL defined in the
// configured datasource" while the app itself ran fine. Load both, in Next's
// precedence order, so the CLI and the runtime always agree.
import { config as loadEnv } from "dotenv";
loadEnv({ path: [".env.local", ".env"] });

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use the direct connection (non-pooled) so migrate/generate CLI commands work.
    // The app runtime uses DATABASE_URL (PgBouncer pooler) via db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
